// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBOXXZ5AoInMIRsVgEOOWYNus4v2sgBuhE',
    appId: '1:644403723677:web:718694790acc795f4a0374',
    messagingSenderId: '644403723677',
    projectId: 'groceries-store-20580',
    authDomain: 'groceries-store-20580.firebaseapp.com',
    storageBucket: 'groceries-store-20580.appspot.com',
    measurementId: 'G-S6YDKV27NZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDJ94_OykOQS3ttv5SAP2EVlEzfMu7eno',
    appId: '1:644403723677:android:84b0044cd84f1af84a0374',
    messagingSenderId: '644403723677',
    projectId: 'groceries-store-20580',
    storageBucket: 'groceries-store-20580.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBOsnujzwMxGkBr_AGXc8fv4cfBz0uPIpc',
    appId: '1:644403723677:ios:c2ec220a6f800c8e4a0374',
    messagingSenderId: '644403723677',
    projectId: 'groceries-store-20580',
    storageBucket: 'groceries-store-20580.appspot.com',
    iosBundleId: 'com.example.groceriesStore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBOsnujzwMxGkBr_AGXc8fv4cfBz0uPIpc',
    appId: '1:644403723677:ios:78f44cfdd02c8c0a4a0374',
    messagingSenderId: '644403723677',
    projectId: 'groceries-store-20580',
    storageBucket: 'groceries-store-20580.appspot.com',
    iosBundleId: 'com.example.groceriesStore.RunnerTests',
  );
}
